### ISSUE TITLE
Support osx-arm64 platform

### ISSUE THREAD

**Issue by nathanweeks** [conda-forge/armadillo-feedstock#40]
It would be great if osx-arm64 could be added as a supported platform.

**Comment by johntruckenbrodt** [comment]
I have opened a PR so the conda-forge bots can automatically trigger the modification of the recipe:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3271

**Comment by henryiii** [comment]
Should be working now! (Thanks @xhochy for the help!)
